### ISSUE TITLE
Issues that make a todomvc video look better

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#150]
Bugs
- [x] new-fiddle doesn't redirect when auto-transact on #149
- [x] auto-transact persist across refresh (local storage) #153

Datomic error related
- [x] Datomic errors are anticipated but look awful and have to scroll sideways to read #152
- [x] new-fiddle query template should put `[?e]` on its own line to emphasize the table-scan

Awkward UX
- [x] markdown anchors should take :rel argument as a keyword, not a string
- [x] can't click on $schema link at 740x480 res
- [x] View panel: Markdown on top, renderer next, then fiddle/css
- [x] fiddle/renderer can be smaller (fit content) and fiddle/markdown can be bigger (fit content), only 480 vh to work with -> fits into 480vh but not including chrome's chrome
- [x] Esc cancel active popover (bc button gets clipped a lot) #126

**Comment by dustingetz** [comment]
Anchor markdown keyword change needs manual migration in prod for 
```
(sources/code-search! "!anchor")
=>
{#uri"datomic:free://datomic:4334/sandbox" #{[17592186045672
                                              :fiddle/markdown
                                              "## TodoMVC with markdown and Datomic\n\n!anchor[New Task](:sys-new-?e)\n\nlist:\n:::\n!value[](0 :todo/completed)\n!value[](0 :todo/title)\n!anchor[Remove](:sys-remove-?e)\n:::\n\n***\n\n#### data view\n\n!table[]"]},
 #uri"datomic:free://datomic:4334/litepay" #{[17592186045886
                                              :fiddle/markdown
                                              "!browse[](summary)\n\n***\n\n## Merchant Home\n\n* !anchor[Send an invoice](send-invoice)\n* !anchor[Request payment](request-payment)\n* !anchor[Point of sale](point-of-sale)"]
                                             [17592186045532
                                              :fiddle/markdown
                                              "## Communication\n\n!cell[](0 :communication/email-address)\n!cell[](0 :communication/mobile-number)\n!cell[](0 :communication/telephone)\n!cell[](0 :communication/telephone2)\n\n# !anchor[](wizard/next)"]
                                             [17592186045502
                                              :fiddle/markdown
                                              "## LitePay superuser dashboard\n* !anchor[Merchant home](merchant-home)\n* !anchor[Create account](signup)\n\n### LitePay Administrator dashboards\n* !anchor[Accounts pending](admin/accounts-pending)\n\n### Superuser (unsafe)\n* !anchor[](admin-account-masterlist)\n* !anchor[](admin-invoice-masterlist)\n* !anchor[](admin.masterlist/ledger)\n\n### Backend dashboards (readonly)\n* !anchor[blockchain state sync](blockchain-state-sync)\n* !anchor[LTC exchange rate](litecoin-ticker)\n"]
                                             [17592186045506
                                              :fiddle/markdown
                                              "## Merchant onboarding\n\ncljs: \n:::\n[:p \"Hello, \" (->> hyperfiddle.core/*ctx* :user-profile :email)] \n:::\n\n!browse[](person-info)\n\n# !anchor[](wizard/next)"]}}

```
