### ISSUE TITLE
UX triage – June

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#282]
Must fix
- [ ] Scrolling + Pushstate interactions #175

Docs related (fixing these makes docs better)
- [ ] Repair xray tooltips on select renderer #12
- [ ] embeds need link/formula tooltips

UX annoyances
- [ ] :link/rel validation
- [ ] fiddle/links should sort by rel https://github.com/hyperfiddle/hyperfiddle/commit/a4a4cd4ee95dc31f6c2383d5146dc4a4aae9cbd9
- [ ] :blank fiddles with buttons need messy bindings #123
- [ ] Schema link from domain panel
- [ ] sort default specified in link/props

Features
- [ ] form validation: datalog, edn, clojure, type, semantic constraints
- [x] suppress "generic confirmation" for most buttons

Low priority
- [ ] Fiddle renderer default values are broken #281
- [ ] link/formula `(fn [ctx] nil)` should just be nil
- [ ] cut/paste edn across fiddles (need diffing engine to generate graph statements)
- [ ] builtin widget that can thumbnail an image with a popover to see bigger

Old
- [x] Toggling fiddle from blank to pull should add a tempid entity #268 
- [x] date picker nil state is wrong (shows today's date) #187
- [x] select options can't pick nil once set #166
- [x] Define behavior when :db/id is missing from pull-expressions #49 
- [x] move domain/home-route fiddle listing back to topnav
- [x] shortcuts menu for top level fiddle routes (see #291)
- [x] :hyperfiddle/new 's auto-fiddle should not get :retract: system-link generation is entirely positional, but it has the fiddle (the fiddle's ident) which can be inspected for semantic hints. We can add a new sys link type :hyperfiddle.system/new and not generate retract for it.
- [x] better link disabled styling

**Comment by dustingetz** [comment]
- [x] better link disabled styling

**Comment by dustingetz** [comment]
Closing this, anything important is either tracked or will come up organically, not looking at this again

**Comment by dustingetz** [comment]
or got fixed already
