### ISSUE TITLE
Simplify :hf classes

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#825]
* [x] affix and new are the same thing. 
* [x] tempid-detached and tempid-from-ctx unify, presence of e (parent) is the signal.
* [x] remove vs detach can be specified by txfn
* [x] rel doesn't mean anything anymore, all links should get auto formula?
* [x] Self is meaningless, just don't specify a class

EAV needs to be robust first (particularly in txfn) i think for this to come together.
- [x] #815 :hypercrud.browser/route should be eav-typed (with metadata instead of ThinEntity) 
- [x] #779 
- [x] Blocked by #826 (there are logic bugs if 826 is not done)
- [ ] make :hypercrud.browser/eav reactive #835
- [x] migration
- [ ] migration: views with hf/rel hf/self etc need to be fixed

Introduced:
- [ ] #833 new-link popover needs redesign, it is awful ux now

Deprecations:
* [x] remove hf/affix (it is equivalent to hf/new)
* [ ] remove legacy tempid APIs
* [x] remove :hf/detach (it is equivalent to hf/new)
* [x] remove rel and self, they are noops
* [x] Disable console links
* [ ] `(fn [_] (hyperfiddle.api/tempid-detached \"$\" ctx))` is implied now

All that is left is :hf/new :hf/remove :hf/iframe

**Comment by dustingetz** [comment]
I broke tempids (second affix): ![image](https://user-images.githubusercontent.com/124158/50048280-d67aa600-0095-11e9-8eac-ca036bbe4663.png)

**Comment by dustingetz** [comment]
hfhf
```
[[:db/retract 17592186060853 :link/class :hf/rel]
 [:db/retract 17592186061852 :link/class :hf/affix]
 [:db/add 17592186061852 :link/class :hf/new]
 [:db/retract 17592186061851 :link/class :hf/affix]
 [:db/add 17592186061851 :link/class :hf/new]
 [:db/retract 17592186061852 :link/class :link]
 [:db/retract 17592186061851 :link/class :fiddle]
 [:db/retract 17592186061849 :link/class :link]
 [:db/retract 17592186061850 :link/class :fiddle-options]
 [:db/retract 17592186061848 :link/class :fiddle]]
```
